name: Simple concept work flow

on:
    workflow_dispatch:

env:
    APP_NAME: "ToDoApp"
    ENVIRONMENT: "Production"

jobs:
    learn:
        runs-on: ubuntu-latest
        steps:
            - name: step1
              run: echo "Hello world! from $APP_NAME"

            - name: step2
              run: echo "Hello world 2 from $APP_NAME in $ENVIRONMENT"

            - name: step3
              run: |
                echo "docker user name is ${{vars.DOCKERHUB_USERNAME}}"
                echo "ec2 User name is ${{vars.EC2_USERNAME}}"

            - name: step4 git checkout   
              uses: actions/checkout@v6

            - name: step5 setup java
              uses: actions/setup-java@v5
              with:
                  java-version: '21'
                  distribution: 'temurin'

            - name: ste6 printing  java version
              run: java -version